2015-06-26T06:25:26.217124+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-06-26T06:25:26.217125+00:00 app[web.1]:     self.callable = self.load()
2015-06-26T06:25:26.217127+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-06-26T06:25:26.217128+00:00 app[web.1]:     return self.load_wsgiapp()
2015-06-26T06:25:26.217129+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-06-26T06:25:26.217130+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-06-26T06:25:26.217131+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2015-06-26T06:25:26.217132+00:00 app[web.1]:     __import__(module)
2015-06-26T06:25:26.217133+00:00 app[web.1]:   File "/app/wsgi.py", line 2, in <module>
2015-06-26T06:25:26.217134+00:00 app[web.1]:     import requests
2015-06-26T06:25:26.217135+00:00 app[web.1]: ImportError: No module named requests
2015-06-26T06:25:26.217172+00:00 app[web.1]: [2015-06-26 06:25:26 +0000] [9] [INFO] Worker exiting (pid: 9)
2015-06-26T06:25:26.232015+00:00 app[web.1]: [2015-06-26 06:25:26 +0000] [10] [INFO] Booting worker with pid: 10
2015-06-26T06:25:26.915059+00:00 heroku[web.1]: State changed from starting to crashed
2015-06-26T06:25:26.897058+00:00 heroku[web.1]: Process exited with status 1
2015-06-26T06:26:14.620362+00:00 heroku[api]: Scale to web=1 by devcode88@gmail.com
2015-06-26T06:26:28.658290+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=shrouded-beach-9987.herokuapp.com request_id=95dce7fb-b572-405c-af5b-38de0ca0d094 fwd="101.222.169.86" dyno= connect= service= status=503 bytes=
2015-06-26T06:26:46.071702+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=shrouded-beach-9987.herokuapp.com request_id=1769c559-1c4b-49f1-b289-b804c4fb24fe fwd="101.222.169.86" dyno= connect= service= status=503 bytes=
2015-06-26T06:34:17.405960+00:00 heroku[slug-compiler]: Slug compilation started
2015-06-26T06:34:17.405969+00:00 heroku[slug-compiler]: Slug compilation finished
2015-06-26T06:34:17.340280+00:00 heroku[api]: Deploy 00e6698 by devcode88@gmail.com
2015-06-26T06:34:17.340280+00:00 heroku[api]: Release v5 created by devcode88@gmail.com
2015-06-26T06:34:17.485182+00:00 heroku[web.1]: State changed from crashed to starting
2015-06-26T06:34:21.132382+00:00 heroku[web.1]: Starting process with command `gunicorn wsgi --log-file -`
2015-06-26T06:34:22.696651+00:00 app[web.1]: [2015-06-26 06:34:22 +0000] [3] [INFO] Starting gunicorn 19.3.0
2015-06-26T06:34:22.697294+00:00 app[web.1]: [2015-06-26 06:34:22 +0000] [3] [INFO] Listening at: http://0.0.0.0:21919 (3)
2015-06-26T06:34:22.715073+00:00 app[web.1]: [2015-06-26 06:34:22 +0000] [10] [INFO] Booting worker with pid: 10
2015-06-26T06:34:22.697389+00:00 app[web.1]: [2015-06-26 06:34:22 +0000] [3] [INFO] Using worker: sync
2015-06-26T06:34:22.706461+00:00 app[web.1]: [2015-06-26 06:34:22 +0000] [9] [INFO] Booting worker with pid: 9
2015-06-26T06:34:22.719037+00:00 app[web.1]: [2015-06-26 06:34:22 +0000] [9] [ERROR] Exception in worker process:
2015-06-26T06:34:22.719042+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2015-06-26T06:34:22.719040+00:00 app[web.1]: Traceback (most recent call last):
2015-06-26T06:34:22.719043+00:00 app[web.1]:     worker.init_process()
2015-06-26T06:34:22.719045+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2015-06-26T06:34:22.719046+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-06-26T06:34:22.719048+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-06-26T06:34:22.719049+00:00 app[web.1]:     self.callable = self.load()
2015-06-26T06:34:22.719051+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-06-26T06:34:22.719052+00:00 app[web.1]:     return self.load_wsgiapp()
2015-06-26T06:34:22.719053+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-06-26T06:34:22.719055+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-06-26T06:34:22.719056+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2015-06-26T06:34:22.719060+00:00 app[web.1]:     import requests
2015-06-26T06:34:22.719057+00:00 app[web.1]:     __import__(module)
2015-06-26T06:34:22.719061+00:00 app[web.1]: ImportError: No module named requests
2015-06-26T06:34:22.719058+00:00 app[web.1]:   File "/app/wsgi.py", line 2, in <module>
2015-06-26T06:34:22.719063+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2015-06-26T06:34:22.719065+00:00 app[web.1]:     worker.init_process()
2015-06-26T06:34:22.719062+00:00 app[web.1]: Traceback (most recent call last):
2015-06-26T06:34:22.719066+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2015-06-26T06:34:22.719067+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-06-26T06:34:22.719068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-06-26T06:34:22.719070+00:00 app[web.1]:     self.callable = self.load()
2015-06-26T06:34:22.719073+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-06-26T06:34:22.719071+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-06-26T06:34:22.719072+00:00 app[web.1]:     return self.load_wsgiapp()
2015-06-26T06:34:22.719074+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-06-26T06:34:22.719077+00:00 app[web.1]:     __import__(module)
2015-06-26T06:34:22.719076+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2015-06-26T06:34:22.719078+00:00 app[web.1]:   File "/app/wsgi.py", line 2, in <module>
2015-06-26T06:34:22.719080+00:00 app[web.1]:     import requests
2015-06-26T06:34:22.719081+00:00 app[web.1]: ImportError: No module named requests
2015-06-26T06:34:22.726306+00:00 app[web.1]: [2015-06-26 06:34:22 +0000] [10] [ERROR] Exception in worker process:
2015-06-26T06:34:22.719131+00:00 app[web.1]: [2015-06-26 06:34:22 +0000] [9] [INFO] Worker exiting (pid: 9)
2015-06-26T06:34:22.726311+00:00 app[web.1]: Traceback (most recent call last):
2015-06-26T06:34:22.726313+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2015-06-26T06:34:22.726314+00:00 app[web.1]:     worker.init_process()
2015-06-26T06:34:22.726316+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2015-06-26T06:34:22.726317+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-06-26T06:34:22.726319+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-06-26T06:34:22.726320+00:00 app[web.1]:     self.callable = self.load()
2015-06-26T06:34:22.726321+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-06-26T06:34:22.726323+00:00 app[web.1]:     return self.load_wsgiapp()
2015-06-26T06:34:22.726324+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-06-26T06:34:22.726325+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-06-26T06:34:22.726327+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2015-06-26T06:34:22.726328+00:00 app[web.1]:     __import__(module)
2015-06-26T06:34:22.726330+00:00 app[web.1]:   File "/app/wsgi.py", line 2, in <module>
2015-06-26T06:34:22.726331+00:00 app[web.1]:     import requests
2015-06-26T06:34:22.726332+00:00 app[web.1]: ImportError: No module named requests
2015-06-26T06:34:22.726334+00:00 app[web.1]: Traceback (most recent call last):
2015-06-26T06:34:22.726336+00:00 app[web.1]:     worker.init_process()
2015-06-26T06:34:22.726335+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2015-06-26T06:34:22.726337+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2015-06-26T06:34:22.726338+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-06-26T06:34:22.726340+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-06-26T06:34:22.726341+00:00 app[web.1]:     self.callable = self.load()
2015-06-26T06:34:22.726342+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-06-26T06:34:22.726344+00:00 app[web.1]:     return self.load_wsgiapp()
2015-06-26T06:34:22.726345+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-06-26T06:34:22.726346+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-06-26T06:34:22.726347+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2015-06-26T06:34:22.726349+00:00 app[web.1]:     __import__(module)
2015-06-26T06:34:22.726350+00:00 app[web.1]:   File "/app/wsgi.py", line 2, in <module>
2015-06-26T06:34:22.726353+00:00 app[web.1]: ImportError: No module named requests
2015-06-26T06:34:22.726351+00:00 app[web.1]:     import requests
2015-06-26T06:34:22.726389+00:00 app[web.1]: [2015-06-26 06:34:22 +0000] [10] [INFO] Worker exiting (pid: 10)
2015-06-26T06:34:22.745693+00:00 app[web.1]: [2015-06-26 06:34:22 +0000] [3] [INFO] Shutting down: Master
2015-06-26T06:34:22.745774+00:00 app[web.1]: [2015-06-26 06:34:22 +0000] [3] [INFO] Reason: Worker failed to boot.
2015-06-26T06:34:23.432225+00:00 heroku[web.1]: Process exited with status 3
2015-06-26T06:34:23.444534+00:00 heroku[web.1]: State changed from starting to crashed
